// js/masterIngredientList.js
// This file contains a master list of common ingredients with predefined categories and units.
// It acts as the "brain" for intelligent pre-filling when creating new inventory items.

export const masterIngredientList = {
  // Frugt & Grønt
  'agurk': { name: 'Agurk', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'avocado': { name: 'Avocado', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'banan': { name: 'Banan', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'blomkål': { name: 'Blomkål', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'broccoli': { name: 'Broccoli', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'chili': { name: 'Chili', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'citron': { name: 'Citron', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'hvidløg': { name: 'Hvidløg', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'ingefær': { name: 'Ingefær', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'g' },
  'kartofler': { name: 'Kartofler', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'g' },
  'lime': { name: 'Lime', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'løg': { name: 'Løg', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'peberfrugt': { name: 'Peberfrugt', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'porre': { name: 'Porre', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'squash': { name: 'Squash', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'tomat': { name: 'Tomat', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'tomater': { name: 'Tomater', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'g' },
  'gulerødder': { name: 'Gulerødder', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'g' },
  'salat': { name: 'Salat', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'spinat': { name: 'Spinat', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'g' },
  'spidskål': { name: 'Spidskål', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'aubergine': { name: 'Aubergine', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'forårsløg': { name: 'Forårsløg', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'persille': { name: 'Persille', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'purløg': { name: 'Purløg', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'basilikum': { name: 'Basilikum', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'æble': { name: 'Æble', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },
  'pære': { name: 'Pære', mainCategory: 'Dagligvarer', subCategory: 'Frugt & Grønt', defaultUnit: 'stk' },

  // Mejeri & Æg
  'æg': { name: 'Æg', mainCategory: 'Dagligvarer', subCategory: 'Mejeri', defaultUnit: 'stk' },
  'mælk': { name: 'Mælk', mainCategory: 'Dagligvarer', subCategory: 'Mejeri', defaultUnit: 'ml' },
  'fløde': { name: 'Fløde', mainCategory: 'Dagligvarer', subCategory: 'Mejeri', defaultUnit: 'ml' },
  'smør': { name: 'Smør', mainCategory: 'Dagligvarer', subCategory: 'Mejeri', defaultUnit: 'g' },
  'ost': { name: 'Ost', mainCategory: 'Dagligvarer', subCategory: 'Mejeri', defaultUnit: 'g' },
  'parmesan': { name: 'Parmesan', mainCategory: 'Dagligvarer', subCategory: 'Mejeri', defaultUnit: 'g' },
  'creme fraiche': { name: 'Creme Fraiche', mainCategory: 'Dagligvarer', subCategory: 'Mejeri', defaultUnit: 'g' },
  'yoghurt': { name: 'Yoghurt', mainCategory: 'Dagligvarer', subCategory: 'Mejeri', defaultUnit: 'g' },
  'skyr': { name: 'Skyr', mainCategory: 'Dagligvarer', subCategory: 'Mejeri', defaultUnit: 'g' },
  'mozzarella': { name: 'Mozzarella', mainCategory: 'Dagligvarer', subCategory: 'Mejeri', defaultUnit: 'g' },
  
  // Kød & Fisk
  'kylling': { name: 'Kylling', mainCategory: 'Dagligvarer', subCategory: 'Kød & Fisk', defaultUnit: 'g' },
  'hakket oksekød': { name: 'Hakket Oksekød', mainCategory: 'Dagligvarer', subCategory: 'Kød & Fisk', defaultUnit: 'g' },
  'hakket svinekød': { name: 'Hakket Svinekød', mainCategory: 'Dagligvarer', subCategory: 'Kød & Fisk', defaultUnit: 'g' },
  'bacon': { name: 'Bacon', mainCategory: 'Dagligvarer', subCategory: 'Kød & Fisk', defaultUnit: 'g' },
  'laks': { name: 'Laks', mainCategory: 'Dagligvarer', subCategory: 'Kød & Fisk', defaultUnit: 'g' },
  'torsk': { name: 'Torsk', mainCategory: 'Dagligvarer', subCategory: 'Kød & Fisk', defaultUnit: 'g' },
  'chorizo': { name: 'Chorizo', mainCategory: 'Dagligvarer', subCategory: 'Kød & Fisk', defaultUnit: 'g' },
  'skinke': { name: 'Skinke', mainCategory: 'Dagligvarer', subCategory: 'Kød & Fisk', defaultUnit: 'g' },

  // Kolonial
  'hvedemel': { name: 'Hvedemel', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },
  'sukker': { name: 'Sukker', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },
  'pasta': { name: 'Pasta', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },
  'ris': { name: 'Ris', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },
  'havregryn': { name: 'Havregryn', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },
  'bouillon': { name: 'Bouillon', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'stk' },
  'flåede tomater': { name: 'Flåede Tomater', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'stk' },
  'hakkede tomater': { name: 'Hakkede Tomater', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'stk' },
  'tomatpuré': { name: 'Tomatpuré', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },
  'kokosmælk': { name: 'Kokosmælk', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'ml' },
  'rugbrød': { name: 'Rugbrød', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'stk' },
  'knækbrød': { name: 'Knækbrød', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'stk' },
  'sennep': { name: 'Sennep', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },
  'ketchup': { name: 'Ketchup', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },
  'mayonnaise': { name: 'Mayonnaise', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },
  'eddike': { name: 'Eddike', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'ml' },
  'olie': { name: 'Olie', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'ml' },
  'olivenolie': { name: 'Olivenolie', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'ml' },
  'sojasauce': { name: 'Sojasauce', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'ml' },
  'honning': { name: 'Honning', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },
  'peanutbutter': { name: 'Peanutbutter', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },
  'mandler': { name: 'Mandler', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },
  'valnødder': { name: 'Valnødder', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },
  'tipo 00': { name: 'Tipo 00 Mel', mainCategory: 'Dagligvarer', subCategory: 'Kolonial', defaultUnit: 'g' },

  // Krydderier
  'salt': { name: 'Salt', mainCategory: 'Dagligvarer', subCategory: 'Krydderier', defaultUnit: 'g' },
  'peber': { name: 'Peber', mainCategory: 'Dagligvarer', subCategory: 'Krydderier', defaultUnit: 'g' },
  'paprika': { name: 'Paprika', mainCategory: 'Dagligvarer', subCategory: 'Krydderier', defaultUnit: 'g' },
  'karry': { name: 'Karry', mainCategory: 'Dagligvarer', subCategory: 'Krydderier', defaultUnit: 'g' },
  'oregano': { name: 'Oregano', mainCategory: 'Dagligvarer', subCategory: 'Krydderier', defaultUnit: 'g' },
  'timian': { name: 'Timian', mainCategory: 'Dagligvarer', subCategory: 'Krydderier', defaultUnit: 'g' },
  'rosmarin': { name: 'Rosmarin', mainCategory: 'Dagligvarer', subCategory: 'Krydderier', defaultUnit: 'g' },
  'kanel': { name: 'Kanel', mainCategory: 'Dagligvarer', subCategory: 'Krydderier', defaultUnit: 'g' },
  'kardemomme': { name: 'Kardemomme', mainCategory: 'Dagligvarer', subCategory: 'Krydderier', defaultUnit: 'g' },
  'spidskommen': { name: 'Spidskommen', mainCategory: 'Dagligvarer', subCategory: 'Krydderier', defaultUnit: 'g' },

  // Frost
  'ærter': { name: 'Ærter (Frost)', mainCategory: 'Dagligvarer', subCategory: 'Frost', defaultUnit: 'g' },
  'spinat (frost)': { name: 'Spinat (Frost)', mainCategory: 'Dagligvarer', subCategory: 'Frost', defaultUnit: 'g' },
  'bær': { name: 'Bær (Frost)', mainCategory: 'Dagligvarer', subCategory: 'Frost', defaultUnit: 'g' },
  'is': { name: 'Is', mainCategory: 'Dagligvarer', subCategory: 'Frost', defaultUnit: 'ml' },

  // Drikkevarer
  'kaffe': { name: 'Kaffe', mainCategory: 'Dagligvarer', subCategory: 'Drikkevarer', defaultUnit: 'g' },
  'the': { name: 'The', mainCategory: 'Dagligvarer', subCategory: 'Drikkevarer', defaultUnit: 'stk' },
  'juice': { name: 'Juice', mainCategory: 'Dagligvarer', subCategory: 'Drikkevarer', defaultUnit: 'ml' },
  'sodavand': { name: 'Sodavand', mainCategory: 'Dagligvarer', subCategory: 'Drikkevarer', defaultUnit: 'ml' },
};
